Add documentation on updating Octue services
octue/octue-sdk-python pull request #683
Opened 2024-10-23 14:52 UTC by cortadocodes

2024-10-24 09:01 UTC, thclark requested changes

2024-10-24 09:01 UTC, thclark commented on docs/source/updating_services.rst
> +10. When you're ready to release the new version of your service, check that the GitHub checks have passed on the latest commit
Also helpful to have a screenshot of what correct tests should look like.

2024-10-24 09:01 UTC, thclark commented on docs/source/updating_services.rst
> +9. When you're ready to review the changes, head to GitHub and open a pull request of your branch into ``main``. Check the diff to make sure everything's there and consistent (it's easy to forget to
You could have a screenshot of a diff

2024-10-24 09:01 UTC, thclark commented on docs/source/updating_services.rst
> +7. Run the tests locally using e.g. ``pytest`` or ``python -m unittest``
you could have a screenshot of pytest output in the terminal, you want all green ticks ;)

2024-10-25 10:10 UTC, cortadocodes commented on docs/source/updating_services.rst
> +   - ``poetry version major`` for a breaking change
Yes I do, it means I don't have to navigate to `pyrpoject.toml` and then to the `version` field and decide which number to update. I think it's really useful!

2024-10-25 10:11 UTC, cortadocodes commented on docs/source/updating_services.rst
> +   - ``poetry version major`` for a breaking change
> Unrelated, we should write a semantic versioning tool for services which automatically versions them based on the JSONSchema in the twine!

Nice, we could factor out what we have in `amy` into a small library that also does that

2024-10-25 10:24 UTC, cortadocodes commented on docs/source/updating_services.rst
> +13. Run a deployment test for the new service revision if you have one
Ok I'll remove that. Is there another good way to test a deployed data service is working? I think the deployment tests are only opinionated in that they use the only backend and deployment method we currently use - pub/sub and cloud run

2024-10-25 10:27 UTC, cortadocodes commented on docs/source/updating_services.rst
> +7. Run the tests locally using e.g. ``pytest`` or ``python -m unittest``
Do you mean test code for the SDK or some kind of generalisable test helpers?

2024-10-25 10:30 UTC, cortadocodes commented on docs/source/updating_services.rst
> +7. Run the tests locally using e.g. ``pytest`` or ``python -m unittest``
I've got a screenshot from `amy`. I think that's ok and doesn't reveal anything private apart from test paths!

2024-10-25 10:34 UTC, cortadocodes commented on docs/source/updating_services.rst
> +       pip install -e .
We should do this over the entire docs

2024-10-25 11:48 UTC, thclark approved these changes

2024-10-25 11:48 UTC, merged